// Dictionary data
const dictionary = {
  A: {
    "Anta": "dia (LK)",
    "Amba": "pasar",
    "Ake, ei": "air",
    "Api, putung": "api",
    "Ai, Aen": "kaki",
    "Ati, Ate": "hati",
    "Ana": "anak",
    "Apo": "paman",
    "Ana seriken": "anak pertama, anak sulung",
    "Aku": "aku, kita",
    "Ani": "belum",
    "adil": "adil",
    "Anuhodo": "juragan",
    "Atasuan": "utusan",
    "Ata, atta": "orang, manusia",
    "ata wine": "seorang perempuan / dia perempuan",
    "Ata tungu": "orang pandai : ata mjaek, pintar, cerdas",
    "Ata pamusu": "bajak, orang membajak sawah: ata pamusu bangga",
    "Atu": "untung",
    "Artina, mbiseri": "dibelakang",
    "Agama": "agama",
    "Ama": "bapak",
    "Aku": "goa, gua",
    "Aka": "akar",
    "Angar": "kapuk",
    "Angelak": "buka",
    "Akhirat": "Akhirat",
    "ajaib": "ajaib",
    "Arwawa, Mbiwaw": "bawah, dibawah",
    "Angar": "kapuk, kapas",
    "apu": "kapur",
    "akala": "akad",
    "Ampa cola": "bayar",
    "Ape": "apa",
    "Amanat": "Amanat",
    "Are'en": "adik",
    "Atta, enda": "orang",
    "Aman": "Aman",
    "Aun": "arti, pahami, memahami",
    "Assu": "anjing",
    "Alamat": "Alamat",
    "Aho": "lambat, lamban",
    "Atengamok": "ngamuk, amuk ; orang mengamuk",
    "Aruna": "nanas",
    "Alam": "Alam",
    "Asli": "asli",
    "Angin": "angin",
    "Awak": "langit",
  },
  B: {
    "Bua": "angkat",
    "Barisa": "lada",
    "Be": "mana",
    "Baka": "luka",
    "Bako": "topi",
    "Balaju": "semangka",
    "Banga, rammeng": "ladang",
    "Blanja": "belanja",
    "Baba": "bisu, gagap, gugup",
    "Bau": "kerbau",
    "Balumbang": "ombak, gelombang",
    "Barat": "barat",
    "Bra": "habis",
    "Bea": "tunggu",
    "Bae, mbae": "pecah",
    "Belu": "lubang",
    "Borot": "kasar",
    "Bonger": "pundak",
    "bore": "pesta",
    "bura": "putih",
    "Beke": "kasih, memberi",
    "Benteng": "benteng",
    "Basa": "tangah malam",
    "Belia": "mahal",
    "Menengguse" : "larangan",
    "Bei": "monyet",
    "Buju": "Tombak",
    "Bara": "bersih",
    "Buso’o": "mencopot",
    "Brune": "Cabai",
    "Bungu": "kening",
    "Bale, sembali, pali": "balik, pulang, kembali",
    "Badara": "bebek",
    "Bulan, wulok": "bulan",
    "Bewi" : "kipas, mengipas",
    "Bangia": "hitung, menghitung",
    "kasunang": "Begitu",
    "Bahagia": "bahagia",
    "Binca": "belah",
    "Binti": "bernapas",
    "Bolok, Antara": "bintang",
    "Bani, bane, mbane": "banyak",
    "Bolang": "buang",
    "Binatang": "binatang",
    "Bangga": "sawah",
    "Babini, bini": "istri, perempuan dewasa",
    "Bapa": "ayah",
    "Bango": "bangau",
    "Beo": "burung beo",
    "Beki": "boleh",
    "Bawa": "bawa",
    "Brei": "bangun",
    "Bulu sumi": "kumis",
    "Bobo barang": "kunang-kunang",
    "Bore, boro": "ramai, Keramaian",
  },
  C: {
    "Cawi" : "mampir",
    "Cura, Bawe" : "bawang",
    "Cango" : "mencabut",
    "Cangker" : "mangkuk",
    "Cofi" : "sapu",
    "Cunga" : "goring",
    "Cembe" : "erat",
    "Calat gawe": "Keliru",
    "Candu" : "muntah",
    "Cio" : "nangis, menangis",
    "Condo" : "salin, menyalin",
    "Celokeloke komina": "terkelupas",
    "Capi" : "sapi, lembu",
    "Compa" : "sampai",
    "Cara, Caron" : "enak, lezat, nikmat",
    "Compa" : "datang",
    "Cici": "Cincin"
  },
  D: {
    "Darua" : "dua",
    "Dewa" : "putra, putri",
    "Dara, raa" : "darah",
    "Dussak" : "Amarah, marah",
    "Deke" : "halus",
    "Duluku" : "lipat",
    "Derisen" : "mula, mulai",
    "Darong" : "bisa",
    "Desi" : "panjang",
    "Dodo" : "berat",
    "Dipok" : "potong, memotong",
    "Dulok" : "gulung",
    "Deke, ndeke" : "kecil, anak kecil",
    "Delu wudu" : "penis",
    "Daraki" : "buruk, kurang baik, kurang bagus",
    "Daran" : "burung dara",
    "Dagangan" : "dagang, jualan",
    "Do’u" : "jauh",
    "Deni" : "mampir, singgah",
    "Den`et": "dekat",
    "Daja" : "arah",
    "Dusse" : "marah",
    "Duam puluh isa" : "dua puluh satu (21)",
    "Durian" : "durian",
    "Dota" : "dinding",
    "Dalok" : "dalam, kedalaman",
    "Datang" : "rampas, merampas",
    "Dalima" : "delima",
  },
  E: {
    "Eloh" : "siang hari",
    "Ena" : "ada",
    "Empo tanga, Mpotak, Ngita" : "mengintip, lihat, melihat",
    "Entok, kayan, ndok" : "duduk",
    "Enbai" : "bayam",
    "Erri" : "pasir",
    "Epa" : "empat",
    "Ese" : "laki-laki",
    "Erum" : "kawan, teman",
    "Enani" : "ini ada",
    "Enane": "itu ada",
    "Ei, ake" : "air",
    "Empon" : "sewa",
    "Epilalu": "kejam",
    "Endok, endo, kampong" : "kampung, Desa, negara",
    "Enda, atta" : "orang",
    "Enggolok" : "kumpul, berkumpul",
  },
  F: {
    "Fare" : "padi",
  },
  G: {
    "Giak" : "bikin, buat, membuat, Nggika = membuat sesuatu",
    "Gelonggor" : "longgar",
    "Gunting" : "gunting",
    "Glep" : "guntur",
    "Gongongon" : "gonggongan",
    "Gla" : "gelas",
    "Gara" : "gagak",
    "Gojo" : "geli",
    "Grampu" : "peluk, memeluk",
    "Gawe, Pegewa, krawe" : "kerja, bekerja, Apesigawe = sedang apa",
    "Gawen" : "sebab",
    "Galupa" : "lupa",
    "Gambir" : "gambir",
    "Golo" : "guling",
  },
  H: {
    "Hebo, Kaboa" : "bohong",
    "Hito, kito" : "disana, sana",
    "Ho" : "iya (kasar)",
    "Hamboeng" : "dari",
    "Hukur" : "ukur",
  },
  I: {
    "Ina, nina" : "ibu",
    "Ina cili" : "ibu tiri",
    "Inatua" : "nenek",
    "matua" : "kakek",
    "Iu" : "rasa",
    "Ina besusu" : "penyusu, menyusu",
    "Iko" : "tali",
    "Isi" : "gigi",
    "Indu" : "hutan",
    "Ikon" : "ekor",
    "Isen" : "biji",
    "Imba" : "gambar, menggambar",
  },
  J: {
    "Ja" : "sekarang",
    "Jampa" : "pelihara",
    "Seng" : "uang, keping",
    "Jembatan" : "jembatan",
    "Jambu" : "jambu",
    "Jaran, Jana" : "kuda",
    "Jati" : "pohon jati",
    "Jaga" : "jaga, menjaga",
    "Jagoang, jano" : "jagung",
    "Jompa" : "dating",
    "Jengkelle" : "melebih, melebihkan, berlebih",
  },
  K: {
    "Kaja" : "malu",
    "kuna" : "ikan",
    "Kambosse" : "bagaimana",
    "kune" : "kendati",
    "Aku": "saya (kasar, tidak dengan sebaya)",
    "kalubu" : "abu",
    "kadodo" : "dodol",
    "kalu" : "bayangan",
    "kula" : "jamur",
    "Kalah" : "kalah",
    "Kelopak": "Kelopak",
    "kutak" : "hutang",
    "kua" : "di (kua uma : di rumah)",
    "Kapa" : "kapas",
    "Kapoa" : "kecebong",
    "Kranjing, Lejo" : "keranjang",
    "Kawanan" : "kanan",
    "Katumbar" : "ketumbar",
    "Karome" : "nakal",
    "Kaban" : "gabus",
    "Ketotok" : "kaget",
    "Kabu’el" : "pancoran",
    "Karassa" : "karang, koral",
    "Karuki" : "kepeting",
    "Keka" : "burung kakatua",
    "Kelakan" : "pancar",
    "Kadale": "kedelai",
    "Kaju, Kaju Cuku" : "kayu, Kayu Bakar",
    "Sugi" : "kaya",
    "Kuku" : "kuku",
    "Kasumba" : "kesumba",
    "Kuwu" : "pondok, gubuk",
    "Koson" : "tidak tau",
    "Katuweng" : "mengantuk, ngantuk",
    "Karong" : "karung",
    "Kanci" : "kunci",
    "Kodo" : "kendor",
    "Karaun (b. bima : lede’)" : "gadung",
    "Ka’e" : "keras",
    "Kandi" : "kendi, lumpang (B. bima : kandei), encok (b. bima) : nocu)",
    "Kartas" : "kertas",
    "Kussu" : "kaku",
    "Kentari" : "bersedia",
    "Kampurot" : "pepaya",
    "Kananga" : "kenanga (bunga)",
    "Kanari" : "kenari (bunga)",
    "Kurung" : "kandang",
    "kune" : "kendati",
    "Kutu" : "kutu",
    "Kapal" : "kapal",
    "Kalambu" : "kelambu",
    "Kabol" : "bisul",
    "Kalakati" : "rahang",
    "Kapoa" : "selamat datang",
    "Kome, komi, Ngkomi" : "engkau, kamu",
    "Kuna" : "ikan",
    "Krame" : "jari",
    "ibu jari" : "inan rima",
    "Telunjuk" : "lima turu",
    "Jari tengah" : "tonga",
    "Jari manis" : "mina",
    "Kelingking" : "deke",
    "Komba" : "belang-belang",
    "Kune anta" : "tidak usah",
    "Kumang" : "makanan",
    "Kota" : "kota",
    "Kiris" : "keris",
    "Kira" : "rindu, mengingat",
    "Kruki" : "kepiting",
    "Kasipau" : "miskin",
    "Kemmi" : "kemiri",
    "Komudi" : "mengemudi, mengendarai",
    "Kamuning" : "kayu kemuni",
    "Kamojo" : "hisap",
    "Kamboi" : "kemana",
    "Kambo’eng" : "(di)/(ke) mana, wanon kambo’eng : dari mana)",
    "Kaweken" : "kiri",
    "Kaju" : "kayu",
    "Kaduru" : "roboh",
    "Kedong" : "kurus",
    "kadera" : "kursi",
    "Kolen" : "merinding",
    "Kitab" : "kitab",
    "Koro’an" : "al-Qur’an",
    "Kikin" : "kikir (alat)",
    "Kitab" : "kitab",
    "Koka" : "nasi",
    "Kawoi" : "pancing, memancing, (b. bima : hawi)",
    "Kukos" : "kukus",
    "Kiwa" : "daging",
    "Kuni" : "kunyit",
    "Kojo" : "geli",
    "Katon" : "Jantung",
  },
  L: {
    "Lima" : "lima",
    "Lumor, lumdur" : "dingin, kedinginan",
    "Luro, liro" : "banting",
    "Lino" : "banjir",
    "Lassa" : "langsat (buah)",
    "Lako" : "pergi",
    "Lako kamboi" : "pergi kemana",
    "Lako letek" : "pergi cepat",
    "Lasa" : "lapang, luas",
    "Loli" : "belut",
    "Lepak" : "kodok",
    "Londe": "daun sirih",
    "Lissu" : "mabuk",
    "Lontak" : "lompat",
    "Lindor" : "gempa",
    "Lewak ape": "untuk apa",
    "Lalu" : "lalat",
    "Lerong" : "keliling",
    "Letta" : "bubur",
    "Lettek" : "roti",
    "Leon" : "lancip, tajam",
    "Loka" : "periuk",
    "Lembo, Tiang" : "perut",
    "Lolo" : "pantat",
    "Loke, roco" : "kupas",
    "Lua" : "lebar",
    "Lea" : "nyala, menyala",
    "Lummong" : "rendam",
    "Lilik, ilo" : "lilin, lampu",
    "Lompokko" : "lepas",
    "Lo’en" : "murah",
    "Loki" : "kulit",
    "Lundok" : "gelap",
    "Lolen" : "kosong",
    "Lio lao" : "pelan-pelan",
    "Lingong" : "bingung",
    "Latta, wiwen" : "pinggir, pinggiran, galangan",
    "Lata" : "ubur-ubur",
    "Lombon" : "baju",
    "Langkalo" : "kaca, cermin",
    "Luju" : "keluar",
    "Linti" : "geger, rusuh",
    "Lopi, sampan" : "perahu, sampan",
    "Lue" : "ujung",
    "Lenu" : "licin",
    "Lorong" : "kebun",
    "Loro" : "keropos",
    "Lunong" : "batal",
    "Lepak" : "katak",
    "Lunca" : "pulau",
    "Lande" : "pinang (buah/pohon)",
    "Luru" : "bantal",
    "Telupo" : "lipan",
    "Lapak" : "laku",
    "Limbi" : "belimbing bulu",
    "Lampar, Lampa" : "tikar, sandal",
    "Lenape" : "mengapa",
    "Lojo" : "malas",
    "Langa-langa" : "laju",
    "Lawa" : "nyanyi, menyanyi, mengaji",
    "Lappe {Lappa)" : "lapar",
    "Linang" : "harta",
    "Loja" : "layar, berlayar",
    "Limbok" : "lumpur",
    "Letek" : "cepat, lekas",
    "Lukok" : "dapur",
    "Lasa" : "bidara",
    "Lio mata" : "pusing",
    "Lolok" : "dubur, pantat",
  },
  M: {
    "Mardeka" : "merdeka",
    "Metiki, Mandu" : "tidur",
    "Manu" : "ayam",
    "Mate, nati" : "mati, meninggal",
    "Matadai" : "matahari",
    "Mantri" : "mentri",
    "Manu ranggo" : "ayam jantan",
    "Manu wine" : "ayam betina",
    "Mawira" : "putih",
    "Mango’on" : "darat, daratan",
    "Muti" : "bicara",
    "Monde" : "akrab",
    "Malu, Marun" : "layu",
    "Manduku" : "Mimpi, bermimpi",
    "Moro" : "obat",
    "Morong" : "(warna) hijau",
    "Manggo" : "kering",
    "Morowisel" : "peluru",
    "Mangi" : "hangus",
    "Maweken" : "gemuk",
    "Mpakak": "letih, lelah",
    "Mpalu" : "Lempar",
    "Mawo": "Mabuk",
    "Mena" : "meja",
    "Meah" : "merah",
    "Mombi" : "mangkudu",
    "Mitung, mutok, Mulong" : "hitam, hitam pekat",
    "Mapia" : "bagus",
    "Mpapa" : "potong",
    "Mondok" : "malam",
    "Menang": "Menang",
    "Mbeda": "mengajak",
    "Maske": "kasihan",
    "Mali" : "tertawa",
    "Meu": "ular",
    "Mbosu" : "kenyang",
    "Mai" : "kemari, kesini, Maete (sopan)",
    "Muto" : "benang",
    "Mokote" : "tampah",
    "Mapu" : "lemah",
    "Mbe" : "kambing",
    "Massi" : "kasihan",
    "Mpondo" : "takut",
    "Muti" : "bahasa",
    "Mesa, Mesan" : "diri, sendiri, sendirian",
    "Meu" : "terserah",
    "Mbau" : "kerbau",
    "Mbonggeng" : "tulang",
    "Mbaso": "Mencuci",
    "Mpele, tungu" : "pintar, pandai",
    "Manuk darodo" : "burung",
    "Mpotak, empo tanga" : "lihat",
    "Mancu" : "sayur",
    "Maa" : "besar",
    "Mina" : "manis",
    "Munte" : "serut",
    "Monek" : "menanam",
    "Mone" : "laki-laki",
    "Meti" : "laut",
    "Mati" : "bunuh",
    "Mo’u" : "jatuh",
    "Mangge" : "asam",
    "Mudu" : "kebakaran",
    "Munen" : "sembunyi",
    "Mpowi" : "rebus",
    "Malli": "Senyuman, Senyum",
    "Mbekingake": "kebal",
    "Mpoja, poja" : "berak",
    "Mawu-Allah" : "Tuhan, Allah",
    "Mapuru" : "seratus",
    "Mba’e" : "pecah",
    "Maca" : "cangkul, mencangkul",
    "Mpali" : "pulang",
    "Menyahut" : "sahut menyahut",
    "Mene, Menek" : "jangan",
    "Mplai, palei" : "lari, berlari",
    "Mbara, pabara" : "bersihkan, membersihkan",
    "Mance, odes" : "rajin",
    "Mangga" : "jangkar",
    "Mbeli" : "beli",
    "Mumong" : "ingus, flu",
    "Monce" : "tanam",
    "Mano" : "pakai",
    "Muti" : "kata",
    "Manjang" : "menjangan, rusa",
    "Mata" : "mata, Ngona mate = main mata",
    "wuton" : "kemaluan laki-laki",
    "Sawe" : "kemaluan wanita",
    "Mati" : "mampus",
    "Mbolang" : "buang",
    "Mberese" : "diatas",
    "Mayit" : "bangkai",
    "Moda" : "gampang, mudah",
    "Mango woko" : "haus, dahaga",
    "Malembu" : "hamil, bunting",
    "Mawa" : "jinak",
    "Mbi wawa, arwawa" : "dibawah",
    "Mata" : "mata",
    "Mbada, Mbarada": "Berbicara, berbicara kotor",
    "Mangusta" : "manggis",
    "Mbengika" : "Kekal, Abadi",
    "Markani" : "perkakas",
    "Mori" : "hidup",
    "Monca" : "kuning",
    "Mpanatei": "kemerau",
    "Muti" : "jeruk",
    "Mono" : "main, bermain",
    "Mondek" : "baik, sembuh",
    "Mancek" : "Alim",
    "Mbi lolol" : "didalam",
    "Mbiseri, artina" : "dibelakang",
  },
  N: {
    "Nati, mate" : "mati",
    "Nassa" : "budak",
    "Niko" : "ikat",
    "Nela" : "lidah",
    "Neo" : "ringan, enteng",
    "Ngenimpe" : "mimpi",
    "Ngaka’a" : "raba, meraba",
    "Nga" : "makan",
    "Ngeri" : "mirip",
    "Ngino" : "minum",
    "Ngale" : "ambil, mengambil",
    "Ngawu" : "keringat",
    "Ntowok" : "diam",
    "Nagara" : "negri",
    "Ngeri" : "pantai",
    "Nggolorong" : "gemuk",
    "Ndupa" : "dupa",
    "Nan`am" : "kakak",
    "Ncancka": "parang",
    "Ne" : "bening, hening",
    "Nyai" : "nyai",
    "Nggusi": "Guci",
    "Nyonya" : "nyonya",
    "Nona" : "nona",
    "Ngawo" : "keringat",
    "Nana" : "getah",
    "nganggo": "konflik",
    "Ngeong" : "kucing",
    "Ngarakan" : "nama, namanya",
    "Ntendi, tendi" : "berdiri",
    "Ngonang" : "bermain, ata ngona = orang bermain, Ata Ngonang Ba = orang sedang bermain bola",
    "Ndiu" : "mandi",
    "Nika" : "menikah, nikah",
    "Ngumba" : "gendong",
    "Ngusi" : "kejar, berburu",
    "Ngak" : "makan",
    "Ngo’e" : "panggil",
    "Ndangga" : "berkelahi",
    "Ndou": "jahit",
    "Ngau": "lembing",
    "Nguse" : "mau",
    "Nong" : "enam",
    "Ngutong" : "bertanya",
    "Ncaru" : "ikut",
    "Ntondak" : "turun",
    "Nasa, Nasam" : "saya, kami (sopan)",
    "Necong": "Lesun",
    "Ngikeaten": "kesal, kekesalan",
    "Ne’eng" : "naik",
    "Ngondok" : "maling, pencuri",
    "Ngewen" : "gantung",
    "Ngelu" : "dapat",
    "Ngawang" : "kasih tau",
    "Ncango" : "goreng",
    "Ntau" : "simpan",
    "Ngutak" : "pinjam",
    "Nenti" : "pegang, memegang",
    "Ngunpo, nggina" : "habis",
    "Nao" : "aren",
    "Ngaka’a" : "dam, bendungan",
    "Ndalo, dalo" : "jalan",
    "Ndai" : "besok",
    "Ngaye" : "malu",
    "Ngante" : "pegang",
    "Ngordong" : "bangsat, brengsek, bejat",
    "Ndeke, deke" : "kecil",
    "Ngoku" : "pungut, memungut",
    "Ncua" : "suruh",
    "Ngilu, Kukus" : "Ngilu, Kecut",
    "Ngurini, nuni" : "bilang, berkata, kasih tau",
    "Ngeda" : "basah",
    "Ngi" : "gigi",
    "Ngusi" : "usir",
    "Nipah" : "nipah",
    "Ngawi" : "gigit",
    "Ngilok" : "gila",
    "Ngumba" : "gendong",
    "Ntasa" : "matang (buah)",
    "Ngalep" : "lambai, melambai",
    "Ngawi, oi kerya" : "keringat",
    "Ngupok" : "genggam",
    "Nambe" : "hilang",
    "Ngika" : "rusak",
    "Ngallok" : "mendidih",
    "Ne’eng, Neget" : "naik",
    "Nare" : "sudah",
    "Ncompa" : "sampai",
    "Ngua": "kasih tau",
    "Ngondok" : "maling, pencuri",
    "Nginong, Nino" : "minum",
    "Niki" : "kalong, kelelawar",
    "Ne’eng" : "panjat",
    "Nina, ina" : "ibu",
    "Ntolan" : "naik diatas",
    "Nculo" : "tenggelam",
    "Ngalek, ngale" : "ambil",
    "Nuncok": "tenun",
    "Ncusa" : "Memotong kecil-kecil",
    "Ngkai" : "kami",
    "Ndadi" : "jadi",
    "Nika iu" : "pingsan",
    "No" : "lagi",
    "Nisi" : "penuh",
    "Nenton" : "menantu",
    "Nemo" : "terbang",
    "Ngondok" : "curi",
    "Ngi’I" : "gusi",
    "Ngoso" : "gosok",
    "Ngarak" : "pikir, melahirkan",
    "kena nako" : "berfikir, pikiran",
    "Ngiu, ncio" : "nangis, menangis",
    "Nali" : "tertawa",
    "Ngiro" : "hidung",
    "Ngoka" : "masak",
    "Ncuku" : "panggang",
  },
  O: {
    "Oret" : "datu, maha raja (sangaji)",
    "Oro" : "pintu, jalan, dengan, {oro sei? : dengan siapa?}",
    "Ou" : "bambu",
    "Ongen" : "lidi",
    "O’or" : "embun",
    "Onake": "ini ada",
    "Onak": "itu saja",
    "Oncano" : "betul adanya",
    "Onen" : "guna, gunakan",
    "Ono" : "lama (sambosi ono : berapa lama)",
    "Omet" : "lintah",
    "Omes mea" : "cengar-cengir",
  },
  P: {
    "Paduka" : "paduka (raja, ratu)",
    "Padak" : "asin",
    "Pa" : "tanduk",
    "Pau" : "mangga",
    "Palana" : "gegabah",
    "Putung, api" : "api",
    "Pare" : "padi",
    "Porek" : "lebah",
    "Pakatu" : "menitip, titip",
    "Pukam" : "punggung",
    "Pani" : "sayap",
    "Peu" : "pijit",
    "Puasa"  : "puasa",
    "Popekon" : "rebung bambu",
    "Pambua" : "pindah",
    "Penabur" : "kecamba",
    "Poter" : "putar, erat-erat",
    "Pusa’at" : "berakhir",
    "Papak" : "papan, papan kayu",
    "Parisa" : "periksa, memeriksa",
    "Prenta" : "perintah",
    "Pertama" : "siriken",
    "Percaya" : "percaya",
    "Punti" : "pisang",
    "Pek" : "perabot",
    "Poe" : "garuk",
    "Pusaka" : "pusaka",
    "Puter" : "pusar",
    "Puso" : "pusat",
    "Pilih" : "pilih",
    "Piler" : "rata, sejajar",
    "Perde, nguku" : "pendek",
    "Pires" : "kapan",
    "Pokon" : "pohon",
    "Mpoka" : "patah",
    "Panjar" : "panjar",
    "Paron" : "gambong, gembong (alat music)",
    "Pamango’o" : "jemur, jemuran, menjemur",
    "Palinga, Lunga" : "dengar, mendengarkan",
    "Panteng" : "gadai",
    "Petu" : "burung perkutut",
    "Poja" : "kotoran",
    "Parrong" : "asap",
    "Pawelek" : "jual",
    "Potok" : "udang",
    "Pacompa" : "sampaikan",
    "Pelepu" : "tarik",
    "Pakumu" : "selimut",
    "Pessu, kenta" : "kentut",
    "Panghulu" : "penghulu",
    "Paroh" : "patuk, mematuk",
    "Patut" : "patut, pantas",
    "Piso" : "buta",
    "Pahiate" : "candagurau, candaan",
    "Pinggung" : "pinggul",
    "Poda" : "pedang",
    "Pandu" : "obor",
    "Pasang" : "pasang",
    "Pai" : "pahit",
    "Pandu" : "lampu",
    "Paloja" : "belajar",
    "Panjong" : "payung",
    "Pea, bea" : "nanti, tunggu",
    "Pawuan" : "muat, muatan",
    "Powe" : "masak",
    "Pabua" : "mesti, harus",
    "Panisi" : "isi, mengisi",
    "Pangrai" : "ingat, mengingat",
    "Parawi" : "binasa, musnah",
    "Pau" : "mangga",
    "Pronu" : "karat",
    "Pangao" : "korek",
    "Penabur" : "mimisan",
    "Po’o, po" : "kepala",
    "Pana" : "panah",
    "Paku" : "paku",
    "Pamor" : "pamor",
    "Panah" : "panah",
    "(ana) panah" : "anak panah",
    "Pana" : "panas",
    "Pundok" : "pandan",
    "Pitu" : "tujuh",
    "Pile" : "perampok, rampok, merampok",
    "Paloja" : "belajar",
    "Pakatu" : "kirim, mengirim",
  },
  R: {
    "Ranga" : "pagar",
    "Rei" : "alang-alang",
    "Rau, utana" : "tanah",
    "Resse" : "atas, ulas, mengulas",
    "Rara" : "pedas",
    "Rencallak" : "salah",
    "Rena" : "kuran",
    "Rui" : "duri",
    "Ralipa" : "diseberang",
    "Rugi" : "rugi",
    "Rata" : "rumput",
    "Rawinana" : "macam-macam (berbuat)",
    "Rua" : "rupa, tampang",
    "Reseri" : "luar",
    "Rengau" : "perang",
    "Rapu" : "Rapat",
    "Rante" : "rantai",
    "Robo naru" : "labu air",
    "Rincot" : "genap",
    "Rene mondo" : "tidak baik, jelek",
    "Rao" : "jarum",
    "Rua" : "muka",
    "Rate" : "kuburan",
    "Rupiya" : "rupiah",
    "Rokan" : "musim",
    "Rammeng, banga" : "ladang",
    "Rokon" : "daun",
    "Ruwa" : "haluan",
    "ruta" : "kacang",
    "Rabe" : "suami",
    "Ringgi" : "uang ringgit",
    "Ruta, Kadale" : "kedelai",
    "Rere" : "baris, berbaris",
    "Rau" : "bumi",
    "Racon" : "racun",
    "Rollor" : "bulat",
  },
  S: {
    "Sara, sarah" : "hukum / peraturan, adat",
    "Senun" : "belajar, mengajar",
    "Salawat" : "sholawat",
    "Sangungawan" : "kami",
    "Sangu wungan" : "segala",
    "Sampu" : "kotor",
    "Soa" : "jahat, taat",
    "Sepo" : "sapu tangan",
    "Sabtu" : "sabtu",
    "Sosanggana" : "sesajen",
    "Sagu" : "sagu",
    "Sene wine" : "berderap, menderap",
    "Saworon" : "majang, memajang",
    "Sebokon" : "jongkok",
    "Sao" : "lawan, melawan",
    "Sambua" : "satu",
    "Pissi" : "sambal",
    "Sawan, bini" : "istri",
    "Suru" : "Semut",
    "Sioh, siwa" : "Sembilan",
    "Saribu, ribu" : "seribu, ribuan",
    "Semuto" : "otak",
    "Sabon" : "sabun",
    "Sigi" : "masjid",
    "Sakali" : "sekali",
    "Selili" : "ketiak",
    "Sedang" : "sedang",
    "Selaka" : "perak",
    "sanggilo" : "ikan gabus",
    "Sabio" : "sedikit",
    "Silen" : "ganti",
    "Sandan" : "santan",
    "Samu" : "mengikat rambut (perempuan)",
    "Sei" : "siapa",
    "Sempolo" : "perawan, gadis",
    "Sugi" : "punya",
    "Sudok, Tli" : "kencing",
    "Serisin" : "gerimis",
    "Sissi" : "karet",
    "Santopa" : "putus",
    "Sangeren" : "rusuk",
    "Samba" : "ular sanca",
    "Sida" : "benar, betul",
    "Senawa" : "berhenti",
    "Sangu" : "Dagu",
    "Sawean" : "disebelah",
    "Selatan" : "selatan",
    "Sadanaba, rowa" : "arit, parit, selokan",
    "Sebolok" : "sebentar",
    "Sompon" : "lumpur",
    "Sarta" : "dia",
    "Sarang" : "sarang",
    "Sungu wangan" : "memang, emang",
    "Surunge" : "kelor",
    "Sando" : "dukun",
    "Sedean, Lawe"  : "demam, sakit parah",
    "Sembossi" : "berapa",
    "Sama" : "sama, sama-sama (juga)",
    "Sia" : "garam",
    "Sambole" : "palu, pemukul, pukul, hantam",
    "Sepepe" : "misan",
    "Selepe" : "ikat pinggang",
    "Samuna" : "juga",
    "Sala" : "bukan",
    "Salindang" : "selendang",
    "Sampula" : "bodoh",
    "Sepatu" : "sepatu",
    "Selu" : "gelang",
    "Sembola" : "pagi",
    "Sembole" : "menyelimuti",
    "Sewun" : "ompong",
    "Sanca" : "parang",
    "Semia" : "begini",
    "Sigeleng" : "tanduk (rusa)",
    "Sampola" : "bujang, lajang",
    "Sandenge" : "sakit",
    "Sanca" : "barang",
    "Singai" : "hari (malam hari, siang hari)",
    "Sangania" : "hari ini",
  },
  T: {
    "Taal" : "pohon lontar",
    "Tiang, Lembo" : "perut",
    "Takiar" : "tangan",
    "Tarau" : "jalu",
    "Telor" : "telur",
    "Tete" : "kena",
    "Totonanga" : "muara, danau",
    "Taruna" : "dulu",
    "Tue" : "kerang",
    "Tui" : "pisau",
    "Tolukom, tuli" : "Telinga",
    "Trata" : "penyu",
    "Tita" : "Kamu (sopan)",
    "Warang" : "Sungai",
    "Taking" : "genit",
    "Tore’en" : "punya",
    "aku tore’en" : "Punya (saya/kita)",
    "Tungu, mpele" : "pintar, cerdas, pandai",
    "Tengapi" : "panggang, memanggang",
    "Tonga po’on" : "uban",
    "Treru" : "kalajengking",
    "Temme/selompi" : "sarung",
    "Tike" : "tokek",
    "Tidu" : "meludah",
    "Tu" : "lutut",
    "Tao" : "ikan (nila)",
    "Tete" : "kena",
    "Tonga" : "nyamuk",
    "Terutung" : "landak",
    "Tolek" : "kuping",
    "Tande" : "kenal",
    "Tupa" : "kelapa",
    "Tengere" : "miring",
    "Tenda" : "terang, gemilang, cerah",
    "Tinang" : "gunung",
    "Tatelu" : "tiga",
    "Teke" : "kecil",
    "Topo’o wo" : "cukur, pangkas rambut, mencukur rambut",
    "Tombu" : "masuk",
    "Timba" : "mayat",
    "Tau mata" : "(seorang/seseorang) laki-laki",
    "Tero" : "atap",
    "Tunu" : "pasang surut",
    "Talla" : "gong",
    "Toto" : "mulut",
    "Toto’on" : "mematuk",
    "Tommon" : "dimuka, didepan, terdepan",
    "Tanuna" : "dahulu",
    "Tunu, Ncuku" : "bakar",
    "Tempi" : "besi",
    "Titi" : "rontok",
    "Tengulu" : "gula",
    "Tawar" : "penawar",
  },
  U: {
    "Uta" : "rambut",
    "Urok" : "hujan",
    "Ula" : "ulat",
    "Uti" : "biawak",
    "Uma" : "rumah",
    "Uncong" : "pikul, memikul",
    "Utara" : "utara",
    "Umur" : "umur",
    "Ua" : "urat",
    "Uncong" : "pikul",
    "Uwi" : "ubi jalar",
    "Urekh" : "arang",
    "Utana, rau" : "tanah",
    "Upen" : "tas",
  },
  W: {
    "Wessu" : "kijang",
    "Wawi, Babat" : "Babi",
    "Watu" : "batu",
    "Warang" : "kali",
    "Wisel" : "senapan, senjata",
    "Walu" : "delapan",
    "Weki" : "badan",
    "Weu" : "baru",
    "Wolo niwa" : "madu",
    "Wani" : "berani",
    "Wante" : "rebus",
    "Winga" : "piring",
    "Wau" : "pohon beringin",
    "Wiwen" : "minggir",
    "Walo" : "biru",
    "Watak" : "batang",
    "Weli" : "beli",
    "Welawa" : "pantun",
    "wokon" : "leher",
    "Wiwi" : "bibir",
    "Waja" : "silet",
    "Wewi" : "kipas",
    "Wele" : "layang-layang, layangan",
    "Walen" : "jujur",
    "Wiwe meti" : "pesisir, pesisir pantai, pesisir laut",
    "Wiwe" : "pesisir",
    "Wulo" : "kasur, kapas",
    "Wouk" : "uap",
    "Wota, bunga" : "bunga",
    "Wulok" : "bulan",
    "Woe" : "bulu",
    "Wai" : "busuk",
    "Wu’e" : "rotan",
    "Wota" : "pucuk bunga, kembang",
    "Welen" : "harga",
    "Wuntu" : "gondok",
    "Wuan" : "buah",
    "Wia" : "semua",
    "Wua, Bua" : "beras",
    "Ware’en" : "separuh, sebahgian",
    "Wuntuf" : "matang (nasi)",
    "Wine" : "perempuan",
  },
};

// Fungsi untuk mencari kata
function searchDictionary() {
  const input = document.getElementById('searchInput');
  const filter = input.value.toUpperCase();
  const dictionaryDiv = document.getElementById('dictionary');
  dictionaryDiv.innerHTML = ''; // Mengosongkan hasil pencarian sebelumnya

  // Iterasi setiap huruf di kamus
  for (const letter in dictionary) {
    const words = dictionary[letter];
    for (const word in words) {
      // Jika kata cocok dengan filter, tampilkan
      if (word.toUpperCase().includes(filter) || words[word].toUpperCase().includes(filter)) {
        const div = document.createElement('div');
        div.innerHTML = `<strong>${word}:</strong> ${words[word]}`;
        dictionaryDiv.appendChild(div);
      }
    }
  }
}
