// Kamus dalam format array objek
const kamusArray = [
    { kata: "dia", terjemahan: "Anta (untuk laki-laki)" },
    { kata: "pasar", terjemahan: "Amba" },
    { kata: "air", terjemahan: "Ake, ei" },
    { kata: "api", terjemahan: "Api" },
    { kata: "arang", terjemahan: "putung" },
    { kata: "kaki", terjemahan: "Ai" },
    { kata: "hati", terjemahan: "Ati" },
    { kata: "anak", terjemahan: "Ana, anak sulung : Ana seriken" },
    { kata: "paman", terjemahan: "Apo" },
    { kata: "anak sulung", terjemahan: "Ana seriken" },
    { kata: "aku", terjemahan: "aku (Kasar), kita (sopan), Nasam (sedang): saya" },
    { kata: "saya", terjemahan: "Nasam, aku (Kasar), kita (sopan)" },
    { kata: "belum", terjemahan: "Ani" },
    { kata: "juragan", terjemahan: "Anuhodo" },
    { kata: "tuan tanah", terjemahan: "Anuhodo" },
    { kata: "utusan", terjemahan: "Atasuan" },
    { kata: "orang", terjemahan: "Ata, enda" },
    { kata: "manusia", terjemahan: "atta" },
    { kata: "pintar", terjemahan: "Mpele (contoh, ata mpele : orang pintar)" },
    { kata: "pandai", terjemahan: "tungu (contoh, Ata tungu : orang pandai)" },
    { kata: "cerdas", terjemahan: "mjaek (contoh, ata mjaek : orang cerdas)" },
    { kata: "sawah", terjemahan: "Bangga (ata pamusu bangga : orang membajak sawah)" },
    { kata: "bajak", terjemahan: "pamusu (Ata pamusu : orang membajak / ata pamusu bangga : orang membajak sawah)" },
    { kata: "membajak", terjemahan: "pamusu (Ata pamusu : orang membajak), (ata pamusu bangga : orang membajak sawah)" },
    { kata: "untung", terjemahan: "Atu" },
    { kata: "laba", terjemahan: "atu" },
    { kata: "belakang", terjemahan: "artina (dibelakang : mbiseri)" },
    { kata: "bapak", terjemahan: "Ama, bapa" },
    { kata: "ayah", terjemahan: "Bapa, Ama" },
    { kata: "goa", terjemahan: "Aku" },
    { kata: "akar", terjemahan: "Aka" },
    { kata: "kapuk", terjemahan: "angar (kapas)" },
    { kata: "kapas", terjemahan: "angar (kapuk), Kapa (kapas)" },
    { kata: "buka", terjemahan: "Angelak" },
    { kata: "bawah", terjemahan: "Mbiwa (arwawa :dibawah)" },
    { kata: "kapur", terjemahan: "apu" },
    { kata: "bayar", terjemahan: "Ampa cola / membayar" },
    { kata: "apa", terjemahan: "Ape" },
    { kata: "arti", terjemahan: "Aun (arti / pahami / memahami)" },
    { kata: "pahami", terjemahan: "aun (arti / pahami / memahami)" },
    { kata: "memahami", terjemahan: "aun (arti / pahami / memahami)" },
    { kata: "anjing", terjemahan: "Assu / asu" },
    { kata: "lambat", terjemahan: "Aho" },
    { kata: "lamban", terjemahan: "Aho" },
    { kata: "pelan", terjemahan: "Aho, Lio (Lio lao : pelan-pelan)" },
    { kata: "mengamuk", terjemahan: "amuk (Atengamok : orang ngamuk)" },
    { kata: "amarah", terjemahan: "Dussak, Marah : Dusse" },
    { kata: "marah", terjemahan: "Dusse, Amarah : Dussak" },
    { kata: "nanas", terjemahan: "Aruna" },
    { kata: "nenas", terjemahan: "Aruna" },
    { kata: "angin", terjemahan: "angin" },
    { kata: "langit", terjemahan: "Awak" },
    { kata: "angkat", terjemahan: "Bua" },
    { kata: "lada", terjemahan: "Barisa" },
    { kata: "mana", terjemahan: "Be" },
    { kata: "luka", terjemahan: "Baka" },
    { kata: "topi", terjemahan: "Bako" },
    { kata: "semangka", terjemahan: "Balaju" },
    { kata: "ladang", terjemahan: "Banga, rammeng" },
    { kata: "belanja", terjemahan: "Blanja" },
    { kata: "bisu", terjemahan: "Baba = (bisu, gagap, gugup)" },
    { kata: "gagap", terjemahan: "Baba = (bisu, gagap, gugup)" },
    { kata: "gugup", terjemahan: "baba = (bisu, gagap, gugup)" },
    { kata: "kerbau", terjemahan: "Bau" },
    { kata: "ombak", terjemahan: "Balumbang" },
    { kata: "gelombang", terjemahan: "Balumbang" },
    { kata: "barat", terjemahan: "barat" },
    { kata: "habis", terjemahan: "Bra" },
    { kata: "tunggu", terjemahan: "Bea" },
    { kata: "pecah", terjemahan: "Bae, mbae" },
    { kata: "lubang", terjemahan: "Belu" },
    { kata: "kasar", terjemahan: "Borot" },
    { kata: "pundak", terjemahan: "Bonger" },
    { kata: "pesta", terjemahan: "bore" },
    { kata: "putih", terjemahan: "bura" },
    { kata: "memberi", terjemahan: "Beke = beri / memberikan, kasih" },
    { kata: "memberikan", terjemahan: "beke" },
    { kata: "benteng", terjemahan: "benteng" },
    { kata: "malam", terjemahan: "Basa" },
    { kata: "mahal", terjemahan: "Belia" },
    { kata: "monyet", terjemahan: "Bei" },
    { kata: "bersih", terjemahan: "Bara" },
    { kata: "copot", terjemahan: "Buso’o" },
    { kata: "mencopot", terjemahan: "buso'o" },
    { kata: "kening", terjemahan: "Bungu" },
    { kata: "pulang", terjemahan: "pali" },
    { kata: "kembali", terjemahan: "bale" },
    { kata: "bebek", terjemahan: "Badara" },
    { kata: "bulan", terjemahan: "wulok, bulan" },
    { kata: "hitung", terjemahan: "Bangia" },
    { kata: "menghitung", terjemahan: "Bangia" },
    { kata: "begitu", terjemahan: "kasunang" },
    { kata: "belah", terjemahan: "Binca" },
    { kata: "bernafas", terjemahan: "Binti" },
    { kata: "bernapas", terjemahan: "Binti" },
    { kata: "nafas", terjemahan: "Binti" },
    { kata: "bintang", terjemahan: "Bolok" },
    { kata: "banyak", terjemahan: "Bani, bane, mbane" },
    { kata: "buang", terjemahan: "Bolang" },
    { kata: "binatang", terjemahan: "binatang" },
    { kata: "perempuan", terjemahan: "Babini" },
    { kata: "istri", terjemahan: "bini" },
    { kata: "bangau", terjemahan: "Bango" },
    { kata: "beo", terjemahan: "beo (burung)" },
    { kata: "boleh", terjemahan: "Beki (bisa : Darong)" },
    { kata: "bisa", terjemahan: "Darong, (boleh : beki)" },
    { kata: "bawa", terjemahan: "bawa (membawa)" },
    { kata: "membawa", terjemahan: "bawa" },
    { kata: "bangun", terjemahan: "Brei" },
    { kata: "kumis", terjemahan: "cumi (bulu : bulu, Bulu cumi = bulu kumis)" },
    { kata: "kunang-kunang", terjemahan: "Bobo barang" },
    { kata: "ramai", terjemahan: "boro (keramaian)" },
    { kata: "keramaian", terjemahan: "boro (ramai)" },
    { kata: "mampir", terjemahan: "Cawi" },
    { kata: "singgah", terjemahan: "Cawi" },
    { kata: "bawang", terjemahan: "Cura" },
    { kata: "mencabut", terjemahan: "Cango" },
    { kata: "cabut", terjemahan: "cango (mencabut)" },
    { kata: "mangkuk", terjemahan: "Cangker" },
    { kata: "mangkok", terjemahan: "Cangker" },
    { kata: "cangkir", terjemahan: "Cangker" },
    { kata: "sapu", terjemahan: "Cofi" },
    { kata: "goreng", terjemahan: "Cunga, ncango" },
    { kata: "erat", terjemahan: "Cembe" },
    { kata: "muntah", terjemahan: "Candu" },
    { kata: "nangis", terjemahan: "Cio" },
    { kata: "menangis", terjemahan: "Cio" },
    { kata: "salin", terjemahan: "Condo (salin, menyalin, memindahkan)" },
    { kata: "pindah", terjemahan: "Pambua" },
    { kata: "sapi", terjemahan: "Capi" },
    { kata: "sampai", terjemahan: "Compa" },
    { kata: "enak", terjemahan: "Cara (enak, lezat, nikmat)" },
    { kata: "lezat", terjemahan: "cara (enak, lezat, nikmat)" },
    { kata: "nikmat", terjemahan: "cara (enak, lezat, nikmat)" },
    { kata: "datang", terjemahan: "Compa, selamat datang : Kapoa" },
    { kata: "selamat datang", terjemahan: "Kapoa" },
    { kata: "dua", terjemahan: "Darua" },
    { kata: "pangeran", terjemahan: "Dewa (laki-laki)" },
    { kata: "darah", terjemahan: "Dara, ra'a" },
    { kata: "halus", terjemahan: "Deke" },
    { kata: "lipat", terjemahan: "Duluku" },
    { kata: "mula", terjemahan: "Derisen (awal, mula, mulai)" },
    { kata: "awal", terjemahan: "Derisen (awal, mula, mulai)" },
    { kata: "mulai", terjemahan: "Derisen (awal, mula, mulai)" },
    { kata: "panjang", terjemahan: "Desi" },
    { kata: "berat", terjemahan: "Dodo" },
    { kata: "potong", terjemahan: "Dipok" },
    { kata: "memotong", terjemahan: "Dipok" },
    { kata: "gulung", terjemahan: "Dulok" },
    { kata: "kecil", terjemahan: "Deke, ndeke" },
    { kata: "penis", terjemahan: "Delu wudu" },
    { kata: "buruk", terjemahan: "Daraki (kurang baik, kurang bagus)" },
    { kata: "dara", terjemahan: "Daran" },
    { kata: "dagang", terjemahan: "Dagangan" },
    { kata: "jualan", terjemahan: "Dagangan" },
    { kata: "jual", terjemahan: "Pawelek" },
    { kata: "jauh", terjemahan: "Do’u" },
    { kata: "dekat", terjemahan: "Deni" },
    { kata: "arah", terjemahan: "Daja" },
    { kata: "dua puluh satu", terjemahan: "Duam puluh isa" },
    { kata: "dua puluh", terjemahan: "Duam puluh" },
    { kata: "satu", terjemahan: "isa" },
    { kata: "durian", terjemahan: "durisa" },
    { kata: "dinding", terjemahan: "Dota" },
    { kata: "tembok", terjemahan: "Dota" },
    { kata: "dalam", terjemahan: "Dalok (kedalaman), Mbi lolol : didalam" },
    { kata: "kedalaman", terjemahan: "Dalok" },
    { kata: "merampas", terjemahan: "Datang, Pile : perampok, rampok, merampok" },
    { kata: "rampas", terjemahan: "Datang, Pile : perampok, rampok, merampok" },
    { kata: "perampok", terjemahan: "pile" },
    { kata: "rampok", terjemahan: "pile" },
    { kata: "merampok", terjemahan: "pile" },
    { kata: "delima", terjemahan: "Dalima" },
    { kata: "siang", terjemahan: "Eloh" },
    { kata: "ada", terjemahan: "Ena" },
    { kata: "lihat", terjemahan: "Mpotak, melihat : Empo tanga" },
    { kata: "melihat", terjemahan: "Empo tanga, lihat : Mpotak" },
    { kata: "duduk", terjemahan: "Entok (halus), kayan (sedang), ndok (kasar)" },
    { kata: "bayam", terjemahan: "Enbai" },
    { kata: "pasir", terjemahan: "Erri" },
    { kata: "empat", terjemahan: "Epa" },
    { kata: "laki-laki", terjemahan: "Ese" },
    { kata: "teman", terjemahan: "Erum, Erri (kawan / teman)" },
    { kata: "kawan", terjemahan: "Erri, Erum (kawan / teman)" },
    { kata: "sewa", terjemahan: "Empon (Menyewa)" },
    { kata: "menyewa", terjemahan: "Empon" },
    { kata: "kampung", terjemahan: "kampong" },
    { kata: "desa", terjemahan: "endo" },
    { kata: "negara", terjemahan: "Endok" },
    { kata: "kumpul", terjemahan: "Enggolok (berkumpul)" },
    { kata: "berkumpul", terjemahan: "Enggolok" },
    { kata: "padi", terjemahan: "Fare" },
    { kata: "bikin", terjemahan: "Giak" },
    { kata: "buat", terjemahan: "Giak" },
    { kata: "membuat", terjemahan: "Giak" },
    { kata: "longgar", terjemahan: "Gelonggor" },
    { kata: "gunting", terjemahan: "gunting" },
    { kata: "guntur", terjemahan: "Glep" },
    { kata: "petir", terjemahan: "Glep" },
    { kata: "gonggongan", terjemahan: "Gongongon" },
    { kata: "gagak", terjemahan: "Gara" },
    { kata: "geli", terjemahan: "Gojo" },
    { kata: "peluk", terjemahan: "grampu, memeluk" },
    { kata: "kerja", terjemahan: "Gawe, krawe" },
    { kata: "bekerja", terjemahan: "Pegewa" },
    { kata: "pekerja", terjemahan: "Pegewa" },
    { kata: "sebab", terjemahan: "Gawen" },
    { kata: "lupa", terjemahan: "Galupa" },
    { kata: "gambir", terjemahan: "Gambir" },
    { kata: "gebah", terjemahan: "Gambir" },
    { kata: "guling", terjemahan: "Golo" },
    { kata: "bohong", terjemahan: "Hebo" },
    { kata: "disana", terjemahan: "Hito, kito : sana" },
    { kata: "sana", terjemahan: "kito, Hito : disana" },
    { kata: "iya", terjemahan: "Ho (kasar)" },
    { kata: "dari", terjemahan: "Hamboeng" },
    { kata: "ukur", terjemahan: "Hukur" },
    { kata: "ibu", terjemahan: "Ina, nina, Ina cili : ibu tiri, Ina besusu : ibu penyusu, mensusu, menyusu (sedang / kata kerja)" },
    { kata: "nenek", terjemahan: "Inatua" },
    { kata: "kakek", terjemahan: "matua" },
    { kata: "rasa", terjemahan: "Iu (rasakan)" },
    { kata: "rasakan", terjemahan: "Iu" },
    { kata: "rasain", terjemahan: "Iu" },
    { kata: "tali", terjemahan: "Iko" },
    { kata: "gigi", terjemahan: "Isi" },
    { kata: "hutan", terjemahan: "Indu" },
    { kata: "ekor", terjemahan: "Ikon" },
    { kata: "biji", terjemahan: "Isen" },
    { kata: "gambar", terjemahan: "Imba" },
    { kata: "menggambar", terjemahan: "Imba" },
    { kata: "Jati", terjemahan: "jati / pohon jati" },
    { kata: "Jambu", terjemahan: "jambu" },
    { kata: "Jaga", terjemahan: "jaga, menjaga" },
    { kata: "menjaga", terjemahan: "menjaga" },
    { kata: "jembatan", terjemahan: "jembatan" },
    { kata: "Kutu", terjemahan: "kutu" },
    { kata: "Kapal", terjemahan: "kapal" },
    { kata: "kelambu", terjemahan: "kalambu" },
    { kata: "kota", terjemahan: "kota" },
    { kata: "kitab", terjemahan: "kitab" },
    { kata: "sekarang", terjemahan: "Ja" },
    { kata: "pelihara", terjemahan: "Jampa" },
    { kata: "uang", terjemahan: "Seng" },
    { kata: "kuda", terjemahan: "Jaran" },
    { kata: "jagung", terjemahan: "Jagoang" },
    { kata: "dating", terjemahan: "Jompa" },
    { kata: "bertemu", terjemahan: "Jompa" },
    { kata: "lebih", terjemahan: "Jengkelle" },
    { kata: "melebihkan", terjemahan: "Jengkelle" },
    { kata: "berlebihan", terjemahan: "Jengkelle" },
    { kata: "malu", terjemahan: "Kaja" },
    { kata: "ikan", terjemahan: "Kuna" },
    { kata: "bagaimana", terjemahan: "Kambosse, Kambose" },
    { kata: "kendati", terjemahan: "kune" },
    { kata: "abu", terjemahan: "kalubu, abu api = abu api / debu" },
    { kata: "dodol", terjemahan: "kadodo" },
    { kata: "bayangan", terjemahan: "kalu" },
    { kata: "jamur", terjemahan: "kula" },
    { kata: "hutang", terjemahan: "kutak" },
    { kata: "di", terjemahan: "kua kua uma : di rumah)" },
    { kata: "kecebong", terjemahan: "Kapoa" },
    { kata: "keranjang", terjemahan: "Kranjing" },
    { kata: "kanan", terjemahan: "Kawanan" },
    { kata: "ketumbar", terjemahan: "Katumbar" },
    { kata: "nakal", terjemahan: "Karome" },
    { kata: "gabus", terjemahan: "Kaban" },
    { kata: "kaget", terjemahan: "Ketotok" },
    { kata: "pancoran", terjemahan: "Kabu’el" },
    { kata: "karang", terjemahan: "Karassa" },
    { kata: "koral", terjemahan: "Karassa" },
    { kata: "keptiting", terjemahan: "Karuki" },
    { kata: "kakatua", terjemahan: "Keka (burung kakaktua)" },
    { kata: "pancar", terjemahan: "Kelakan" },
    { kata: "kayu", terjemahan: "Kaju" },
    { kata: "kaya", terjemahan: "Sugi" },
    { kata: "kuku", terjemahan: "kuku" },
    { kata: "kesumba", terjemahan: "Kasumba" },
    { kata: "hena", terjemahan: "Kasumba" },
    { kata: "pondok", terjemahan: "Kuwu" },
    { kata: "gubuk", terjemahan: "Kuwu" },
    { kata: "tidak tau", terjemahan: "Koson" },
    { kata: "tidak tahu", terjemahan: "Koson" },
    { kata: "mengantuk", terjemahan: "Katuweng" },
    { kata: "ngantuk", terjemahan: "Katuweng" },
    { kata: "karung", terjemahan: "Karong" },
    { kata: "kunci", terjemahan: "Kanci" },
    { kata: "kendor", terjemahan: "Kodo" },
    { kata: "longgar", terjemahan: "Kodo" },
    { kata: "gadung", terjemahan: "Karaun(b. bima : lede’)" },
    { kata: "lede", terjemahan: "Karaun" },
    { kata: "keras", terjemahan: "Ka’e" },
    { kata: "kendi", terjemahan: "Kandi (b. bima : kandei, lumpang : tempayang, encok b. bima : nocu)" },
    { kata: "tempayang", terjemahan: "lumpang" },
    { kata: "kertas", terjemahan: "Kartas" },
    { kata: "kaku", terjemahan: "Kussu" },
    { kata: "bersedia", terjemahan: "Kentari" },
    { kata: "pepaya", terjemahan: "Kampurot" },
    { kata: "bunga", terjemahan: "bunga, seperti bunga Kananga, Kanari" },
    { kata: "kenanga", terjemahan: "Kananga = bunga" },
    { kata: "kenari", terjemahan: "Kanari = bunga" },
    { kata: "kandang", terjemahan: "Kurung" },
    { kata: "kendati", terjemahan: "Kune" },
    { kata: "bisul", terjemahan: "Kabol" },
    { kata: "rahang", terjemahan: "Kalakati" },
    { kata: "engkau", terjemahan: "kome (sopan)" },
    { kata: "kamu", terjemahan: "komi (sedang)" },
    { kata: "jari", terjemahan: "Krame (ibu jari : inan rima, Telunjuk : lima turu, Jari tengah : tonga, Jari manis : mina, Kelingking : deke)" },
    { kata: "belang", terjemahan: "Komba (warna)" },
    { kata: "belang-belang", terjemahan: "Komba" },
    { kata: "tidak", terjemahan: "kune, Kune anta : tidak usah, koso : tidak Tau" },
    { kata: "makan", terjemahan: "Kumang" },
    { kata: "keris", terjemahan: "Kiris" },
    { kata: "rindu", terjemahan: "Kira" },
    { kata: "kangen", terjemahan: "Kira" },
    { kata: "mengingat", terjemahan: "Kira" },
    { kata: "kepiting", terjemahan: "Kruki, karuki" },
    { kata: "miskin", terjemahan: "Kasipahu" },
    { kata: "kemiri", terjemahan: "Kemmi" },
    { kata: "kayu", terjemahan: "Kaji, Kaji Kamuning : kayu kemuning, kaji jambu : kayu jambu" },
    { kata: "jambu", terjemahan: "jambu" },
    { kata: "hisap", terjemahan: "Kamojo" },
    { kata: "menghisap", terjemahan: "Kamojo" },
    { kata: "kemana", terjemahan: "Kamboi, Lako kamboi : pergi kemana, Kambo’eng : mana, wanon kambo’eng : dari mana" },
    { kata: "pergi", terjemahan: "Lako, Lako kamboi : pergi kemana, Lako letek : pergi cepat" },
    { kata: "pergi kemana", terjemahan: "Lako kamboi" },
    { kata: "pergi cepat", terjemahan: "lako letek" },
    { kata: "cepat", terjemahan: "letek" },
    { kata: "bergegas", terjemahan: "letek" },
    { kata: "lekas", terjemahan: "lekas (cepat)" },
    { kata: "kiri", terjemahan: "Kaweken" },
    { kata: "roboh", terjemahan: "Kaduru" },
    { kata: "kurus", terjemahan: "Kedong" },
    { kata: "merinding", terjemahan: "Kolen" },
    { kata: "al-qur’an", terjemahan: "koro'an" },
    { kata: "quran", terjemahan: "koro'an" },
    { kata: "qur'an", terjemahan: "koro'an" },
    { kata: "kikir", terjemahan: "kikin (alat)" },
    { kata: "nasi", terjemahan: "koka" },
    { kata: "pancing", terjemahan: "Kawoi, b. bima : hawi" },
    { kata: "kukus", terjemahan: "Kukos" },
    { kata: "daging", terjemahan: "kiwa" },
    { kata: "kunyit", terjemahan: "kuni" },
    { kata: "geli", terjemahan: "Kojo" },
    { kata: "lima", terjemahan: "lima" },
    { kata: "dingin", terjemahan: "Lumor, lumdur : kedinginan" },
    { kata: "banting", terjemahan: "Luro" },
    { kata: "banjir", terjemahan: "Lino" },
    { kata: "langsat", terjemahan: "Lassa" },
    { kata: "luas", terjemahan: "Lasa" },
    { kata: "belut", terjemahan: "Loli" },
    { kata: "kodok", terjemahan: "Lepak" },
    { kata: "mabuk", terjemahan: "Lissu" },
    { kata: "lompat", terjemahan: "Lontak" },
    { kata: "gempa", terjemahan: "Lindor" },
    { kata: "lalat", terjemahan: "Lalu" },
    { kata: "keliling", terjemahan: "Lerong" },
    { kata: "putar", terjemahan: "Lerong" },
    { kata: "bubur", terjemahan: "Letta" },
    { kata: "roti", terjemahan: "Lettek" },
    { kata: "lancip", terjemahan: "Leon" },
    { kata: "periuk", terjemahan: "Loka" },
    { kata: "perut", terjemahan: "Lembo" },
    { kata: "pantat", terjemahan: "Lolo" },
    { kata: "kupas", terjemahan: "Loke, roco" },
    { kata: "lebar", terjemahan: "Lua" },
    { kata: "nyala", terjemahan: "Lea" },
    { kata: "menyala", terjemahan: "Lea" },
    { kata: "rendam", terjemahan: "Lummong" },
    { kata: "lilin", terjemahan: "Lilik, ilo" },
    { kata: "lampu", terjemahan: "ilo" },
    { kata: "lepas", terjemahan: "Lompokko" },
    { kata: "murah", terjemahan: "Lo’en" },
    { kata: "kulit", terjemahan: "Loki" },
    { kata: "gelap", terjemahan: "Lundok" },
    { kata: "kosong", terjemahan: "Lolen" },
    { kata: "bingung", terjemahan: "Lingong" },
    { kata: "pinggir", terjemahan: "Latta, wiwen / pinggiran, galangan" },
    { kata: "ubur-ubur", terjemahan: "Lata" },
    { kata: "baju", terjemahan: "Lombon" },
    { kata: "kaca", terjemahan: "Langkalo" },
    { kata: "cermin", terjemahan: "Langkalo" },
    { kata: "keluar", terjemahan: "Luju" },
    { kata: "geger", terjemahan: "Linti" },
    { kata: "rusuh", terjemahan: "Linti" },
    { kata: "perahu", terjemahan: "Lopi" },
    { kata: "sampan", terjemahan: "sampan" },
    { kata: "ujung", terjemahan: "Lue" },
    { kata: "licin", terjemahan: "Lenu" },
    { kata: "kebun", terjemahan: "Lorong" },
    { kata: "keropos", terjemahan: "Loro" },
    { kata: "katak", terjemahan: "Lepak" },
    { kata: "pulau", terjemahan: "Lunca" },
    { kata: "lidah", terjemahan: "Nela" },
    { kata: "ringan", terjemahan: "Neo" },
    { kata: "mimpi", terjemahan: "Ngenimpe" },
    { kata: "meraba", terjemahan: "Ngaka’a" },
    { kata: "makan", terjemahan: "Nga" },
    { kata: "mirip", terjemahan: "Ngeri" },
    { kata: "minum", terjemahan: "Ngino" },
    { kata: "ambil", terjemahan: "Ngale" },
    { kata: "mengambil", terjemahan: "Ngale" },
    { kata: "keringat", terjemahan: "Ngawu" },
    { kata: "diam", terjemahan: "Ntowok" },
    { kata: "negri", terjemahan: "Nagara" },
    { kata: "pantai", terjemahan: "Ngeri" },
    { kata: "dupa", terjemahan: "Ndupa" },
    { kata: "bening", terjemahan: "Ne" },
    { kata: "hening", terjemahan: "Ne" },
    { kata: "nyai", terjemahan: "Nyai" },
    { kata: "nyonya", terjemahan: "Nyonya" },
    { kata: "nona", terjemahan: "Nona" },
    { kata: "getah", terjemahan: "Nana" },
    { kata: "kucing", terjemahan: "Ngeong" },
    { kata: "nama", terjemahan: "Ngarakan / = namanya" },
    { kata: "berdiri", terjemahan: "Ntendi, tendi" },
    { kata: "bermain", terjemahan: "ngongang ata ngona (orang bermain)" },
    { kata: "mandi", terjemahan: "Ndiu" },
    { kata: "nikah", terjemahan: "Nika" },
    { kata: "gendong", terjemahan: "Ngumba" },
    { kata: "berburu", terjemahan: "Ngusi" },
    { kata: "kejar", terjemahan: "Ngusi" },
    { kata: "makan", terjemahan: "Ngak" },
    { kata: "panggil", terjemahan: "Ngo’e" },
    { kata: "mau", terjemahan: "Nguse" },
    { kata: "enam", terjemahan: "Nong" },
    { kata: "bertanya", terjemahan: "Ngutong" },
    { kata: "ikut", terjemahan: "Ncaru" },
    { kata: "turun", terjemahan: "Ntondak" },
    { kata: "naik", terjemahan: "Ne’eng" },
    { kata: "pencuri", terjemahan: "Ngondok" },
    { kata: "maling", terjemahan: "Ngondok" },
    { kata: "gantung", terjemahan: "Ngewen" },
    { kata: "dapat", terjemahan: "Ngelu" },
    { kata: "kasih tau", terjemahan: "Ngawang" },
    { kata: "simpan", terjemahan: "Ntau" },
    { kata: "pinjam", terjemahan: "Ngutak" },
    { kata: "pegang", terjemahan: "Nenti" },
    { kata: "memegang", terjemahan: "Nenti" },
    { kata: "habis", terjemahan: "Ngunpo, nggina" },
    { kata: "aren", terjemahan: "Nao" },
    { kata: "bendungan", terjemahan: "Ngaka’a" },
    { kata: "jalan", terjemahan: "Ndalo, dalo" },
    { kata: "besok", terjemahan: "Ndai" },
    { kata: "malu", terjemahan: "Ngaye" },
    { kata: "pegang", terjemahan: "Ngante" },
    { kata: "bangsat", terjemahan: "Ngordong" },
    { kata: "brengsek", terjemahan: "Ngordong" },
    { kata: "bejat", terjemahan: "Ngordong" },
    { kata: "Kecil", terjemahan: "Ndeke, deke" },
    { kata: "pungut", terjemahan: "Ngoku" },
    { kata: "memungut", terjemahan: "Ngoku" },
    { kata: "puruh", terjemahan: "Ncua" },
    { kata: "ngilu", terjemahan: "Ngilu" },
    { kata: "kecut", terjemahan: "Ngilu" },
    { kata: "bilang", terjemahan: "Ngurini" },
    { kata: "berkata", terjemahan: "nuni" },
    { kata: "basah", terjemahan: "Ngeda" },
    { kata: "gigi", terjemahan: "Ngi" },
    { kata: "usir", terjemahan: "Ngusi" },
    { kata: "nipah", terjemahan: "Nipah" },
    { kata: "gigit", terjemahan: "Ngawi" },
    { kata: "gila", terjemahan: "Ngilok" },
    { kata: "gendong", terjemahan: "Ngumba" },
    { kata: "matang", terjemahan: "Ntasa" },
    { kata: "melambai", terjemahan: "Ngalep" },
    { kata: "keringat", terjemahan: "Ngawi, oi kerya" },
    { kata: "genggam", terjemahan: "Ngupok" },
    { kata: "rawa-rawa", terjemahan: "Ndalo" },
    { kata: "hilang", terjemahan: "Nambe" },
    { kata: "rusak", terjemahan: "Ngika" },
    { kata: "mendidih", terjemahan: "Ngallok" },
    { kata: "minum", terjemahan: "Nginong" },
    { kata: "kalong", terjemahan: "Niki" },
    { kata: "kelelawar", terjemahan: "Niki" },
    { kata: "panjat", terjemahan: "Ne’eng" },
    { kata: "ibu", terjemahan: "Nina, ina" },
    { kata: "ambil", terjemahan: "Ngalek, ngale" },
    { kata: "kami", terjemahan: "Ngkai" },
    { kata: "jadi", terjemahan: "Ndadi" },
    { kata: "pingsan", terjemahan: "Nika iu" },
    { kata: "lagi", terjemahan: "No" },
    { kata: "penuh", terjemahan: "Nisi" },
    { kata: "menantu", terjemahan: "Nenton" },
    { kata: "terbang", terjemahan: "Nemo" },
    { kata: "curi", terjemahan: "Ngondok" },
    { kata: "gusi", terjemahan: "Ngi’I" },
    { kata: "gosok", terjemahan: "Ngoso" },
    { kata: "pikir", terjemahan: "kena nako = berfikir, pikiran" },
    { kata: "melahirkan", terjemahan: "Ngarak" },
    { kata: "menangis", terjemahan: "Ngiu, ncio" },
    { kata: "nangis", terjemahan: "Ngiu, ncio" },
    { kata: "tertawa", terjemahan: "Nali" },
    { kata: "hidung", terjemahan: "Ngiro" },
    { kata: "masak", terjemahan: "Ngoka" },
    { kata: "panggang", terjemahan: "Ncuku" },
    { kata: "pohon pinang", terjemahan: "Lande" },
    { kata: "pinang", terjemahan: "Lande" },
    { kata: "bantal", terjemahan: "Luru" },
    { kata: "lipan", terjemahan: "Telupo" },
    { kata: "laku", terjemahan: "Lapak" },
    { kata: "belimbing bulu", terjemahan: "Limbi" },
    { kata: "tikar", terjemahan: "Lampa" },
    { kata: "sandal", terjemahan: "Lampa" },
    { kata: "mengapa", terjemahan: "Lenape" },
    { kata: "malas", terjemahan: "Lojo" },
    { kata: "laju", terjemahan: "Langa-langa" },
    { kata: "menyanyi", terjemahan: "Lawa" },
    { kata: "lapar", terjemahan: "Lappa" },
    { kata: "harta", terjemahan: "Linang" },
    { kata: "berlayar", terjemahan: "Loja" },
    { kata: "lumpur", terjemahan: "Limbok" },
    { kata: "dapur", terjemahan: "Lukok" },
    { kata: "bidara", terjemahan: "Lasa" },
    { kata: "pusing", terjemahan: "Lio mata" },
    { kata: "pantat", terjemahan: "Lolok / Dubur" },
    { kata: "merdeka", terjemahan: "Mardeka" },
    { kata: "Tidur", terjemahan: "Metiki, Mandu" },
    { kata: "ayam", terjemahan: "Manuk" },
    { kata: "Ayam jantan", terjemahan: "Manuk ranggo" },
    { kata: "Ayam betina", terjemahan: "Manuk wine" },
    { kata: "mati", terjemahan: "mate" },
    { kata: "meninggal", terjemahan: "nati" },
    { kata: "matahari", terjemahan: "Matadai" },
    { kata: "mentri", terjemahan: "Mantri" },
    { kata: "putih", terjemahan: "Mawira" },
    { kata: "daratan", terjemahan: "Mango’on" },
    { kata: "bicara", terjemahan: "Muti" },
    { kata: "bagi", terjemahan: "Monde" },
    { kata: "layu", terjemahan: "Malu" },
    { kata: "obat", terjemahan: "Moro" },
    { kata: "hijau", terjemahan: "Morong" },
    { kata: "kering", terjemahan: "Manggo" },
    { kata: "peluru", terjemahan: "Morowisel" },
    { kata: "hangus", terjemahan: "Mangi" },
    { kata: "gemuk", terjemahan: "Maweken" },
    { kata: "merah", terjemahan: "Meah" },
    { kata: "mengkudu", terjemahan: "Mombi" },
    { kata: "hitam", terjemahan: "Mitung, mutok, Mulong" },
    { kata: "bagus", terjemahan: "Mapia" },
    { kata: "potong", terjemahan: "Mpapa" },
    { kata: "malam", terjemahan: "Mondok" },
    { kata: "tertawa", terjemahan: "Mali" },
    { kata: "kesini", terjemahan: "Mai / kemari" },
    { kata: "benang", terjemahan: "Muto" },
    { kata: "lemah", terjemahan: "Mapu" },
    { kata: "kambing", terjemahan: "Mbe" },
    { kata: "kasihan", terjemahan: "Massi" },
    { kata: "takut", terjemahan: "Mpondo" },
    { kata: "bahasa", terjemahan: "Muti" },
    { kata: "sendiri", terjemahan: "Mesa" },
    { kata: "sendirian", terjemahan: "Mesan" },
    { kata: "terserah", terjemahan: "Meu" },
    { kata: "kerbau", terjemahan: "Mbau" },
    { kata: "burung", terjemahan: "Manuk darodo" },
    { kata: "lihat", terjemahan: "Mpotak, empo tanga" },
    { kata: "sayur", terjemahan: "Mancu" },
    { kata: "Besar", terjemahan: "Maa" },
    { kata: "manis", terjemahan: "Mina" },
    { kata: "laki-laki", terjemahan: "Mone" },
    { kata: "Laut", terjemahan: "Meti" },
    { kata: "bunuh", terjemahan: "Mati" },
    { kata: "jatuh", terjemahan: "Mo’u" },
    { kata: "asam", terjemahan: "Mangge" },
    { kata: "kebakaran", terjemahan: "Mudu" },
    { kata: "sembunyi", terjemahan: "Munen" },
    { kata: "rebus", terjemahan: "Mpowi" },
    { kata: "berak", terjemahan: "Mpoja, poja" },
    { kata: "tuhan", terjemahan: "Mawu-Allah" },
    { kata: "seratus", terjemahan: "Mapuru" },
    { kata: "pecah", terjemahan: "Mba’e" },
    { kata: "cangkul", terjemahan: "Maca" },
    { kata: "mencangkul", terjemahan: "Maca" },
    { kata: "pulang", terjemahan: "Mpali" },
    { kata: "sahut", terjemahan: "Menyahut" },
    { kata: "jangan", terjemahan: "Mene, Menek" },
    { kata: "lari", terjemahan: "Mplai" },
    { kata: "berlari", terjemahan: "palei" },
    { kata: "bersihkan", terjemahan: "Mbara" },
    { kata: "membersihkan", terjemahan: "pabara" },
    { kata: "rajin", terjemahan: "Mance, odes" },
    { kata: "jangkar", terjemahan: "Mangga" },
    { kata: "beli", terjemahan: "Mbeli" },
    { kata: "ingus", terjemahan: "Mumong" },
    { kata: "flu", terjemahan: "Mumong" },
    { kata: "tanam", terjemahan: "Monce" },
    { kata: "pakai", terjemahan: "Mano" },
    { kata: "kata", terjemahan: "Muti" },
    { kata: "rusa", terjemahan: "Manjang" },
    { kata: "mata", terjemahan: "Mata" },
    { kata: "kemaluan", terjemahan: "Wuton = alat kelamin (laki-laki), Sawe = Kemaluan wanita" },
    { kata: "mampus", terjemahan: "Mati" },
    { kata: "buang", terjemahan: "Mbolang" },
    { kata: "diatas", terjemahan: "Mberese" },
    { kata: "bangkai", terjemahan: "Mayit" },
    { kata: "gampang", terjemahan: "Moda" },
    { kata: "mudah", terjemahan: "Moda" },
    { kata: "haus", terjemahan: "Mango woko" },
    { kata: "hamil", terjemahan: "Malembu" },
    { kata: "bunting", terjemahan: "Malembu" },
    { kata: "jinak", terjemahan: "Mawa" },
    { kata: "dibawah", terjemahan: "Mbi wawa, arwawa" },
    { kata: "mata", terjemahan: "Mata" },
    { kata: "manggis", terjemahan: "Mangusta" },
    { kata: "perkakas", terjemahan: "Markani" },
    { kata: "hidup", terjemahan: "Mori" },
    { kata: "kuning", terjemahan: "Monca" },
    { kata: "jeruk", terjemahan: "Muti" },
    { kata: "bermain", terjemahan: "Mono" },
    { kata: "baik", terjemahan: "Mondek" },
    { kata: "mati", terjemahan: "Nati, Mate" },
    { kata: "budak", terjemahan: "Nassa" },
    { kata: "ikat", terjemahan: "Niko" },
    { kata: "raja", terjemahan: "Oret" },
    { kata: "pintu", terjemahan: "Oro" },
    { kata: "jalan", terjemahan: "Oru" },
    { kata: "siapa", terjemahan: "Sei" },
    { kata: "dengan siapa", terjemahan: "Oro sei" },
    { kata: "bambu", terjemahan: "Ou" },
    { kata: "lidi", terjemahan: "Ongen" },
    { kata: "embun", terjemahan: "O’or" },
    { kata: "guna", terjemahan: "Onen / = beruna,gunakan" },
    { kata: "berapa lama", terjemahan: "Sambosi ono" },
    { kata: "lama", terjemahan: "Ono" },
    { kata: "berapa", terjemahan: "Sambosi" },
    { kata: "lintah", terjemahan: "Omet" },
    { kata: "cengar-cengir", terjemahan: "Omes mea" },
    { kata: "paduka", terjemahan: "Paduka" },
    { kata: "asin", terjemahan: "Padak" },
    { kata: "tanduk", terjemahan: "Pa" },
    { kata: "mangga", terjemahan: "Pau" },
    { kata: "gegabah", terjemahan: "Palana" },
    { kata: "api", terjemahan: "Putung, api" },
    { kata: "lebah", terjemahan: "Porek" },
    { kata: "sayap", terjemahan: "Pani" },
    { kata: "pijit", terjemahan: "Peu" },
    { kata: "puasa", terjemahan: "Puasa" },
    { kata: "rebung", terjemahan: "Popekon" },
    { kata: "kecamba", terjemahan: "Penabur" },
    { kata: "putar", terjemahan: "Poter" },
    { kata: "berakhir", terjemahan: "Pusa’at" }

    // ... (Tambahkan lebih banyak kata di sini)
];

// Fungsi untuk mencari terjemahan
function cariTerjemahan() {
    const inputKata = document.getElementById("search-input").value.toLowerCase();
    const resultDiv = document.getElementById("result");

    // Mencari kata dalam array kamusArray
    const kataDitemukan = kamusArray.find(item => item.kata === inputKata);

    if (kataDitemukan) {
        resultDiv.innerHTML = `<p>Terjemahan dari "${inputKata}" adalah "${kataDitemukan.terjemahan}".</p>`;
    } else {
        resultDiv.innerHTML = `<p>Kata "${inputKata}" tidak ditemukan dalam kamus.</p>`;
    }
}

// Mengurutkan kamusArray berdasarkan kata (alfabetis)
kamusArray.sort((a, b) => a.kata.localeCompare(b.kata));

// Event listener untuk tombol pencarian
document.getElementById("search-button").addEventListener("click", cariTerjemahan);
